DROP TABLE IF EXISTS tartist;
DROP TABLE IF EXISTS talbum;
DROP TABLE IF EXISTS tsong;

CREATE TABLE tartist (
aID INT NOT NULL PRIMARY KEY,
aalias TEXT DEFAULT 'unknown');

CREATE TABLE talbum (
dID INT NOT NULL PRIMARY KEY,
dname TEXT NOT NULL DEFAULT 'unknown',
aID INT NOT NULL,
FOREIGN KEY(aID) REFERENCES tartist(aID));

CREATE TABLE tsong (
cID INT NOT NULL PRIMARY KEY,
tsongname TEXT NOT NULL,
tchords TEXT NOT NULL,
trhythm TEXT NOT NULL,
tfavchord TEXT NOT NULL,
tbasechord TEXT NOT NULL,
dID INT NOT NULL,
FOREIGN KEY(dID) REFERENCES talbum(dID));
